apiVersion: v1
kind: Secret
metadata:
  name: poundcake-secrets
  labels:
    {{- include "poundcake-standalone.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
stringData:
  DB_ROOT_PASSWORD: {{ default (randAlphaNum 24) .Values.secrets.dbRootPassword | quote }}
  DB_NAME: {{ .Values.secrets.dbName | quote }}
  DB_USER: {{ .Values.secrets.dbUser | quote }}
  DB_PASSWORD: {{ default (randAlphaNum 24) .Values.secrets.dbPassword | quote }}
  RABBITMQ_USER: {{ .Values.secrets.rabbitmqUser | quote }}
  RABBITMQ_PASSWORD: {{ default (randAlphaNum 24) .Values.secrets.rabbitmqPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: stackstorm-secrets
  labels:
    {{- include "poundcake-standalone.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
stringData:
  MONGO_ROOT_PASSWORD: {{ default (randAlphaNum 24) .Values.secrets.mongoRootPassword | quote }}
  MONGO_USERNAME: {{ .Values.secrets.mongoUsername | quote }}
  MONGO_PASSWORD: {{ default (randAlphaNum 24) .Values.secrets.mongoPassword | quote }}
  RABBITMQ_USER: {{ .Values.secrets.rabbitmqUser | quote }}
  RABBITMQ_PASSWORD: {{ default (randAlphaNum 24) .Values.secrets.rabbitmqPassword | quote }}
  ST2_AUTH_USER: {{ .Values.secrets.st2AuthUser | quote }}
  ST2_AUTH_PASSWORD: {{ default (randAlphaNum 24) .Values.secrets.st2AuthPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: stackstorm-apikeys
  labels:
    {{- include "poundcake-standalone.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-19"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
stringData:
  st2_api_key: ""
