"""Immutable ingredient templates advertised by the dummy service plugin."""

from __future__ import annotations

from api.plugins.contract import health_check_operation_parameters
from api.types import JSONObject


DUMMY_COMMUNICATION_PAYLOAD_SCHEMA: JSONObject = {
    "type": "object",
    "properties": {
        "title": {"type": "string"},
        "description": {"type": "string"},
        "message": {"type": "string"},
        "source": {"type": "string"},
        "context": {"type": "object"},
    },
    "required": ["title", "description", "message", "source", "context"],
    "additionalProperties": False,
}


DUMMY_INGREDIENT_TEMPLATES: tuple[JSONObject, ...] = (
    {
        "service_type": "dummy",
        "service_exec": "health_check",
        "destination_target": "dummy",
        "task_key_template": "dummy-health-check",
        "payload_schema": {
            "type": "object",
            "properties": {},
            "additionalProperties": False,
        },
        "service_payload_template": {},
        "service_exec_parameters": health_check_operation_parameters(),
        "default_expected_secs": 1,
        "default_timeout": 30,
        "service_exec_expected_outcome_default": {"status": "healthy"},
        "ingredient_purpose": "plugin_health",
        "is_blocking": True,
        "retry_count": 0,
        "retry_delay": 0,
        "on_failure": "continue",
    },
    {
        "service_type": "dummy",
        "service_exec": "positive_result",
        "destination_target": "dummy",
        "task_key_template": "dummy-positive-result",
        "payload_schema": {
            "type": "object",
            "properties": {
                "message": {"type": "string", "minLength": 1},
                "correlation_id": {"type": "string"},
            },
            "required": ["message"],
            "additionalProperties": False,
        },
        "service_payload_template": {
            "message": "dummy positive service result",
            "correlation_id": "{{ order.req_id }}",
        },
        "default_expected_secs": 1,
        "default_timeout": 30,
        "service_exec_expected_outcome_default": {"success": True},
        "ingredient_purpose": "utility",
        "is_blocking": True,
        "retry_count": 0,
        "retry_delay": 0,
        "on_failure": "stop",
    },
    {
        "service_type": "dummy",
        "service_exec": "negative_result",
        "destination_target": "dummy",
        "task_key_template": "dummy-negative-result",
        "payload_schema": {
            "type": "object",
            "properties": {
                "message": {"type": "string", "minLength": 1},
                "correlation_id": {"type": "string"},
            },
            "required": ["message"],
            "additionalProperties": False,
        },
        "service_payload_template": {
            "message": "dummy negative service result",
            "correlation_id": "{{ order.req_id }}",
        },
        "default_expected_secs": 1,
        "default_timeout": 30,
        "service_exec_expected_outcome_default": {"success": True},
        "ingredient_purpose": "utility",
        "is_blocking": True,
        "retry_count": 0,
        "retry_delay": 0,
        "on_failure": "stop",
    },
    {
        "service_type": "dummy",
        "service_exec": "negative_result",
        "destination_target": "dummy",
        "task_key_template": "dummy-expected-negative-result",
        "payload_schema": {
            "type": "object",
            "properties": {
                "message": {"type": "string", "minLength": 1},
                "correlation_id": {"type": "string"},
            },
            "required": ["message"],
            "additionalProperties": False,
        },
        "service_payload_template": {
            "message": "dummy expected negative service result",
            "correlation_id": "{{ order.req_id }}",
        },
        "default_expected_secs": 1,
        "default_timeout": 30,
        "service_exec_expected_outcome_default": {"success": False},
        "ingredient_purpose": "utility",
        "is_blocking": True,
        "retry_count": 0,
        "retry_delay": 0,
        "on_failure": "stop",
    },
    {
        "service_type": "dummy",
        "service_exec": "slow_result",
        "destination_target": "dummy",
        "task_key_template": "dummy-slow-cancel-result",
        "payload_schema": {
            "type": "object",
            "properties": {
                "message": {"type": "string", "minLength": 1},
                "correlation_id": {"type": "string"},
            },
            "required": ["message"],
            "additionalProperties": False,
        },
        "service_payload_template": {
            "message": "dummy slow cancel service result",
            "correlation_id": "{{ order.req_id }}",
        },
        "default_expected_secs": 60,
        "default_timeout": 300,
        "service_exec_expected_outcome_default": {"success": True},
        "ingredient_purpose": "remediation",
        "is_blocking": True,
        "retry_count": 0,
        "retry_delay": 0,
        "on_failure": "stop",
    },
    {
        "service_type": "dummy",
        "service_exec": "fast_result",
        "destination_target": "dummy",
        "task_key_template": "dummy-fast-result",
        "payload_schema": {
            "type": "object",
            "properties": {
                "message": {"type": "string", "minLength": 1},
                "correlation_id": {"type": "string"},
            },
            "required": ["message"],
            "additionalProperties": False,
        },
        "service_payload_template": {
            "message": "dummy fast result service execution",
            "correlation_id": "{{ order.req_id }}",
        },
        "default_expected_secs": 1,
        "default_timeout": 30,
        "service_exec_expected_outcome_default": {"success": True},
        "ingredient_purpose": "utility",
        "is_blocking": True,
        "retry_count": 0,
        "retry_delay": 0,
        "on_failure": "stop",
    },
    {
        "service_type": "dummy",
        "service_exec": "sleep_10",
        "destination_target": "dummy",
        "task_key_template": "dummy-sleep-10",
        "payload_schema": {
            "type": "object",
            "properties": {
                "message": {"type": "string", "minLength": 1},
                "correlation_id": {"type": "string"},
            },
            "required": ["message"],
            "additionalProperties": False,
        },
        "service_payload_template": {
            "message": "dummy sleep 10 service result",
            "correlation_id": "{{ order.req_id }}",
        },
        "default_expected_secs": 10,
        "default_timeout": 60,
        "service_exec_expected_outcome_default": {"success": True},
        "ingredient_purpose": "utility",
        "is_blocking": True,
        "retry_count": 0,
        "retry_delay": 0,
        "on_failure": "stop",
    },
    {
        "service_type": "dummy",
        "service_exec": "communication",
        "destination_target": "dummy",
        "task_key_template": "dummy-comms",
        "payload_schema": DUMMY_COMMUNICATION_PAYLOAD_SCHEMA,
        "service_payload_template": {},
        "service_exec_parameters": {
            "operation": "open",
            "allowed_operations": ["open", "notify", "update", "close"],
            "operation_metadata": {
                "open": {
                    "label": "Open",
                    "description": "Create a communication thread.",
                    "payload_schema": DUMMY_COMMUNICATION_PAYLOAD_SCHEMA,
                },
                "notify": {
                    "label": "Notify",
                    "description": "Add a notification.",
                    "payload_schema": DUMMY_COMMUNICATION_PAYLOAD_SCHEMA,
                },
                "update": {
                    "label": "Update",
                    "description": "Update an existing thread.",
                    "payload_schema": DUMMY_COMMUNICATION_PAYLOAD_SCHEMA,
                },
                "close": {
                    "label": "Close",
                    "description": "Close an existing thread.",
                    "payload_schema": DUMMY_COMMUNICATION_PAYLOAD_SCHEMA,
                },
            },
        },
        "default_expected_secs": 1,
        "default_timeout": 30,
        "service_exec_expected_outcome_default": {"success": True},
        "ingredient_purpose": "comms",
        "is_blocking": False,
        "retry_count": 0,
        "retry_delay": 0,
        "on_failure": "continue",
    },
)


DUMMY_RECIPE_TEMPLATES: tuple[JSONObject, ...] = (
    {
        "name": "plugin-health-check:dummy",
        "description": "Scheduled health check for the dummy service plugin.",
        "enabled": True,
        "recipe_ingredients": [
            {
                "service_type": "dummy",
                "service_exec": "health_check",
                "destination_target": "dummy",
                "task_key_template": "dummy-health-check",
                "step_order": 1,
                "on_success": "continue",
                "parallel_group": 0,
                "depth": 0,
                "service_payload": {},
                "service_exec_expected_secs": 1,
                "service_exec_timeout": 30,
                "service_exec_expected_outcome": {"status": "healthy"},
                "run_phase": "firing",
                "run_condition": "always",
            }
        ],
    },
    {
        "name": "dummy-scheduled-positive-result",
        "description": "Scheduled dummy service execution using the normal order path.",
        "enabled": True,
        "recipe_ingredients": [
            {
                "service_type": "dummy",
                "service_exec": "positive_result",
                "destination_target": "dummy",
                "task_key_template": "dummy-positive-result",
                "step_order": 1,
                "on_success": "continue",
                "parallel_group": 0,
                "depth": 0,
                "service_payload": {
                    "message": "dummy scheduled service execution",
                    "correlation_id": "{{ order.req_id }}",
                },
                "service_exec_expected_secs": 1,
                "service_exec_timeout": 30,
                "service_exec_expected_outcome": {"success": True},
                "run_phase": "firing",
                "run_condition": "always",
            }
        ],
    },
    {
        "name": "dummy-positive-result",
        "description": "Managed contract recipe for the dummy positive service result.",
        "enabled": True,
        "recipe_ingredients": [
            {
                "service_type": "dummy",
                "service_exec": "positive_result",
                "destination_target": "dummy",
                "task_key_template": "dummy-positive-result",
                "step_order": 1,
                "on_success": "continue",
                "parallel_group": 0,
                "depth": 0,
                "service_payload": {
                    "message": "dummy positive recipe processed {{ order.req_id }}",
                    "correlation_id": "{{ order.req_id }}",
                },
                "service_exec_expected_secs": 1,
                "service_exec_timeout": 30,
                "service_exec_expected_outcome": {"success": True},
                "run_phase": "both",
                "run_condition": "always",
            }
        ],
    },
    {
        "name": "dummy-negative-result",
        "description": "Managed contract recipe for the dummy negative service result.",
        "enabled": True,
        "recipe_ingredients": [
            {
                "service_type": "dummy",
                "service_exec": "negative_result",
                "destination_target": "dummy",
                "task_key_template": "dummy-negative-result",
                "step_order": 1,
                "on_success": "continue",
                "parallel_group": 0,
                "depth": 0,
                "service_payload": {
                    "message": "dummy negative recipe processed {{ order.req_id }}",
                    "correlation_id": "{{ order.req_id }}",
                },
                "service_exec_expected_secs": 1,
                "service_exec_timeout": 30,
                "service_exec_expected_outcome": {"success": True},
                "run_phase": "both",
                "run_condition": "always",
            }
        ],
    },
    {
        "name": "dummy-expected-negative-result",
        "description": (
            "Managed contract recipe proving an expected negative service result "
            "is a PoundCake success."
        ),
        "enabled": True,
        "recipe_ingredients": [
            {
                "service_type": "dummy",
                "service_exec": "negative_result",
                "destination_target": "dummy",
                "task_key_template": "dummy-expected-negative-result",
                "step_order": 1,
                "on_success": "continue",
                "parallel_group": 0,
                "depth": 0,
                "service_payload": {
                    "message": "dummy expected negative recipe processed {{ order.req_id }}",
                    "correlation_id": "{{ order.req_id }}",
                },
                "service_exec_expected_secs": 1,
                "service_exec_timeout": 30,
                "service_exec_expected_outcome": {"success": False},
                "run_phase": "both",
                "run_condition": "always",
            }
        ],
    },
    {
        "name": "dummy-slow-cancel-result",
        "description": "Managed contract recipe proving resolved alerts cancel active firing work.",
        "enabled": True,
        "recipe_ingredients": [
            {
                "service_type": "dummy",
                "service_exec": "slow_result",
                "destination_target": "dummy",
                "task_key_template": "dummy-slow-cancel-result",
                "step_order": 1,
                "on_success": "continue",
                "parallel_group": 0,
                "depth": 0,
                "service_payload": {
                    "message": "dummy slow cancel recipe processed {{ order.req_id }}",
                    "correlation_id": "{{ order.req_id }}",
                },
                "service_exec_expected_secs": 60,
                "service_exec_timeout": 300,
                "service_exec_expected_outcome": {"success": True},
                "run_phase": "firing",
                "run_condition": "always",
            },
            {
                "service_type": "dummy",
                "service_exec": "fast_result",
                "destination_target": "dummy",
                "task_key_template": "dummy-fast-result",
                "step_order": 1,
                "on_success": "continue",
                "parallel_group": 0,
                "depth": 1,
                "service_payload": {
                    "message": "dummy resolving phase complete for {{ order.req_id }}",
                    "correlation_id": "{{ order.req_id }}",
                },
                "service_exec_expected_secs": 1,
                "service_exec_timeout": 30,
                "service_exec_expected_outcome": {"success": True},
                "run_phase": "resolving",
                "run_condition": "always",
            },
        ],
    },
    {
        "name": "dummy-parallel-slow-cancel-result",
        "description": (
            "Managed contract recipe proving resolved alerts cancel every in-flight row "
            "in an active parallel group."
        ),
        "enabled": True,
        "recipe_ingredients": [
            {
                "service_type": "dummy",
                "service_exec": "slow_result",
                "destination_target": "dummy",
                "task_key_template": "dummy-slow-cancel-result",
                "step_order": 1,
                "on_success": "continue",
                "parallel_group": 1,
                "depth": 1,
                "service_payload": {
                    "message": "dummy parallel slow cancel A processed {{ order.req_id }}",
                    "correlation_id": "{{ order.req_id }}",
                },
                "service_exec_expected_secs": 60,
                "service_exec_timeout": 300,
                "service_exec_expected_outcome": {"success": True},
                "run_phase": "firing",
                "run_condition": "always",
            },
            {
                "service_type": "dummy",
                "service_exec": "slow_result",
                "destination_target": "dummy",
                "task_key_template": "dummy-slow-cancel-result",
                "step_order": 1,
                "on_success": "continue",
                "parallel_group": 1,
                "depth": 1,
                "service_payload": {
                    "message": "dummy parallel slow cancel B processed {{ order.req_id }}",
                    "correlation_id": "{{ order.req_id }}",
                },
                "service_exec_expected_secs": 60,
                "service_exec_timeout": 300,
                "service_exec_expected_outcome": {"success": True},
                "run_phase": "firing",
                "run_condition": "always",
            },
            {
                "service_type": "dummy",
                "service_exec": "fast_result",
                "destination_target": "dummy",
                "task_key_template": "dummy-fast-result",
                "step_order": 1,
                "on_success": "continue",
                "parallel_group": 0,
                "depth": 1,
                "service_payload": {
                    "message": "dummy resolving phase complete for {{ order.req_id }}",
                    "correlation_id": "{{ order.req_id }}",
                },
                "service_exec_expected_secs": 1,
                "service_exec_timeout": 30,
                "service_exec_expected_outcome": {"success": True},
                "run_phase": "resolving",
                "run_condition": "always",
            },
        ],
    },
    {
        "name": "dummy-multi-group-blocking-result",
        "description": (
            "Managed contract recipe proving Timer reconciliation advances Cook across "
            "multiple parallel groups and a blocking middle step."
        ),
        "enabled": True,
        "recipe_ingredients": [
            {
                "service_type": "dummy",
                "service_exec": "positive_result",
                "destination_target": "dummy",
                "task_key_template": "dummy-positive-result",
                "step_order": 1,
                "on_success": "continue",
                "parallel_group": 1,
                "depth": 1,
                "service_payload": {
                    "message": "dummy multi group first A processed {{ order.req_id }}",
                    "correlation_id": "{{ order.req_id }}",
                },
                "service_exec_expected_secs": 1,
                "service_exec_timeout": 30,
                "service_exec_expected_outcome": {"success": True},
                "run_phase": "both",
                "run_condition": "always",
            },
            {
                "service_type": "dummy",
                "service_exec": "positive_result",
                "destination_target": "dummy",
                "task_key_template": "dummy-positive-result",
                "step_order": 1,
                "on_success": "continue",
                "parallel_group": 1,
                "depth": 1,
                "service_payload": {
                    "message": "dummy multi group first B processed {{ order.req_id }}",
                    "correlation_id": "{{ order.req_id }}",
                },
                "service_exec_expected_secs": 1,
                "service_exec_timeout": 30,
                "service_exec_expected_outcome": {"success": True},
                "run_phase": "both",
                "run_condition": "always",
            },
            {
                "service_type": "dummy",
                "service_exec": "positive_result",
                "destination_target": "dummy",
                "task_key_template": "dummy-positive-result",
                "step_order": 2,
                "on_success": "continue",
                "parallel_group": 2,
                "depth": 2,
                "service_payload": {
                    "message": "dummy multi group blocking step processed {{ order.req_id }}",
                    "correlation_id": "{{ order.req_id }}",
                },
                "service_exec_expected_secs": 1,
                "service_exec_timeout": 30,
                "service_exec_expected_outcome": {"success": True},
                "run_phase": "both",
                "run_condition": "always",
            },
            {
                "service_type": "dummy",
                "service_exec": "positive_result",
                "destination_target": "dummy",
                "task_key_template": "dummy-positive-result",
                "step_order": 3,
                "on_success": "continue",
                "parallel_group": 3,
                "depth": 3,
                "service_payload": {
                    "message": "dummy multi group final A processed {{ order.req_id }}",
                    "correlation_id": "{{ order.req_id }}",
                },
                "service_exec_expected_secs": 1,
                "service_exec_timeout": 30,
                "service_exec_expected_outcome": {"success": True},
                "run_phase": "both",
                "run_condition": "always",
            },
            {
                "service_type": "dummy",
                "service_exec": "positive_result",
                "destination_target": "dummy",
                "task_key_template": "dummy-positive-result",
                "step_order": 3,
                "on_success": "continue",
                "parallel_group": 3,
                "depth": 3,
                "service_payload": {
                    "message": "dummy multi group final B processed {{ order.req_id }}",
                    "correlation_id": "{{ order.req_id }}",
                },
                "service_exec_expected_secs": 1,
                "service_exec_timeout": 30,
                "service_exec_expected_outcome": {"success": True},
                "run_phase": "both",
                "run_condition": "always",
            },
        ],
    },
    {
        "name": "dummy-prior-blocking-sleep10-result",
        "description": (
            "Stress recipe with prior blocking groups and dummy sleep_10 steps that hold "
            "plugin dispatch responses for 10 seconds before Timer advances the dish."
        ),
        "enabled": True,
        "recipe_ingredients": [
            {
                "service_type": "dummy",
                "service_exec": "sleep_10",
                "destination_target": "dummy",
                "task_key_template": "dummy-sleep-10",
                "step_order": 1,
                "on_success": "continue",
                "parallel_group": 1,
                "depth": 1,
                "service_payload": {
                    "message": "dummy sleep stress step 1 processed {{ order.req_id }}",
                    "correlation_id": "{{ order.req_id }}",
                },
                "service_exec_expected_secs": 30,
                "service_exec_timeout": 180,
                "service_exec_expected_outcome": {"success": True},
                "run_phase": "firing",
                "run_condition": "always",
            },
            {
                "service_type": "dummy",
                "service_exec": "sleep_10",
                "destination_target": "dummy",
                "task_key_template": "dummy-sleep-10",
                "step_order": 2,
                "on_success": "continue",
                "parallel_group": 2,
                "depth": 2,
                "service_payload": {
                    "message": "dummy sleep stress step 2 processed {{ order.req_id }}",
                    "correlation_id": "{{ order.req_id }}",
                },
                "service_exec_expected_secs": 30,
                "service_exec_timeout": 180,
                "service_exec_expected_outcome": {"success": True},
                "run_phase": "firing",
                "run_condition": "always",
            },
            {
                "service_type": "dummy",
                "service_exec": "sleep_10",
                "destination_target": "dummy",
                "task_key_template": "dummy-sleep-10",
                "step_order": 3,
                "on_success": "continue",
                "parallel_group": 3,
                "depth": 3,
                "service_payload": {
                    "message": "dummy sleep stress step 3 processed {{ order.req_id }}",
                    "correlation_id": "{{ order.req_id }}",
                },
                "service_exec_expected_secs": 30,
                "service_exec_timeout": 180,
                "service_exec_expected_outcome": {"success": True},
                "run_phase": "firing",
                "run_condition": "always",
            },
        ],
    },
    {
        "name": "dummy-multi-group-preblock-failure-result",
        "description": (
            "Managed contract recipe proving a blocking failure in an early parallel "
            "group cancels downstream blocked steps."
        ),
        "enabled": True,
        "recipe_ingredients": [
            {
                "service_type": "dummy",
                "service_exec": "positive_result",
                "destination_target": "dummy",
                "task_key_template": "dummy-positive-result",
                "step_order": 1,
                "on_success": "continue",
                "parallel_group": 1,
                "depth": 1,
                "service_payload": {
                    "message": "dummy preblock failure positive processed {{ order.req_id }}",
                    "correlation_id": "{{ order.req_id }}",
                },
                "service_exec_expected_secs": 1,
                "service_exec_timeout": 30,
                "service_exec_expected_outcome": {"success": True},
                "run_phase": "both",
                "run_condition": "always",
            },
            {
                "service_type": "dummy",
                "service_exec": "negative_result",
                "destination_target": "dummy",
                "task_key_template": "dummy-negative-result",
                "step_order": 1,
                "on_success": "continue",
                "parallel_group": 1,
                "depth": 1,
                "service_payload": {
                    "message": "dummy preblock failure negative processed {{ order.req_id }}",
                    "correlation_id": "{{ order.req_id }}",
                },
                "service_exec_expected_secs": 1,
                "service_exec_timeout": 30,
                "service_exec_expected_outcome": {"success": True},
                "run_phase": "both",
                "run_condition": "always",
            },
            {
                "service_type": "dummy",
                "service_exec": "positive_result",
                "destination_target": "dummy",
                "task_key_template": "dummy-positive-result",
                "step_order": 2,
                "on_success": "continue",
                "parallel_group": 2,
                "depth": 2,
                "service_payload": {
                    "message": "dummy preblock blocked middle processed {{ order.req_id }}",
                    "correlation_id": "{{ order.req_id }}",
                },
                "service_exec_expected_secs": 1,
                "service_exec_timeout": 30,
                "service_exec_expected_outcome": {"success": True},
                "run_phase": "both",
                "run_condition": "always",
            },
            {
                "service_type": "dummy",
                "service_exec": "positive_result",
                "destination_target": "dummy",
                "task_key_template": "dummy-positive-result",
                "step_order": 3,
                "on_success": "continue",
                "parallel_group": 3,
                "depth": 3,
                "service_payload": {
                    "message": "dummy preblock blocked final A processed {{ order.req_id }}",
                    "correlation_id": "{{ order.req_id }}",
                },
                "service_exec_expected_secs": 1,
                "service_exec_timeout": 30,
                "service_exec_expected_outcome": {"success": True},
                "run_phase": "both",
                "run_condition": "always",
            },
            {
                "service_type": "dummy",
                "service_exec": "positive_result",
                "destination_target": "dummy",
                "task_key_template": "dummy-positive-result",
                "step_order": 3,
                "on_success": "continue",
                "parallel_group": 3,
                "depth": 3,
                "service_payload": {
                    "message": "dummy preblock blocked final B processed {{ order.req_id }}",
                    "correlation_id": "{{ order.req_id }}",
                },
                "service_exec_expected_secs": 1,
                "service_exec_timeout": 30,
                "service_exec_expected_outcome": {"success": True},
                "run_phase": "both",
                "run_condition": "always",
            },
        ],
    },
)


DUMMY_COMMUNICATION_ROUTES: tuple[JSONObject, ...] = (
    {
        "id": "dummy-global-comms",
        "label": "Dummy Global Comms",
        "service_type": "dummy",
        "destination_target": "dummy",
        "provider_config": {},
        "enabled": True,
        "position": 1,
    },
)


DUMMY_SCHEDULED_TASKS: tuple[JSONObject, ...] = (
    {
        "task_key": "plugin-health-check:dummy",
        "task_type": "plugin_health_check",
        "service_type": "dummy",
        "service_exec": "health_check",
        "task_parameters": health_check_operation_parameters(),
        "source": "plugin_manifest",
        "is_enabled": True,
        "run_interval_seconds": 30,
        "priority": 20,
        "timeout_seconds": 30,
        "task_payload": {},
        "expected_outcome": {"status": "healthy"},
    },
    {
        "task_key": "dummy-scheduled-positive-result",
        "task_type": "service_execution",
        "service_type": "dummy",
        "service_exec": "positive_result",
        "source": "plugin_manifest",
        "is_enabled": True,
        "run_interval_seconds": 300,
        "priority": 100,
        "timeout_seconds": 30,
        "task_payload": {
            "message": "dummy scheduled service execution",
            "correlation_id": "SYSTEM-DISHWASHER",
        },
        "task_parameters": {},
        "expected_outcome": {"success": True},
    },
)
