{{- if .Values.auth.enabled }}
---
{{- $secretName := printf "%s-admin" (include "poundcake.fullname" .) }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- $adminPassword := "" }}
{{- if $existingSecret }}
  {{- $adminPassword = index $existingSecret.data "password" | b64dec }}
{{- else }}
  {{- $adminPassword = randAlphaNum 24 }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "poundcake.labels" . | nindent 4 }}
  annotations:
    {{- include "poundcake.preInstallSecretAnnotations" . | nindent 4 }}
type: Opaque
data:
  username: {{ "admin" | b64enc | quote }}
  password: {{ $adminPassword | b64enc | quote }}
{{- end }}
