#!/bin/bash
set -euo pipefail

: "${MYSQL_ROOT_PASSWORD:?MYSQL_ROOT_PASSWORD required}"
: "${MYSQL_DATABASE:?MYSQL_DATABASE required}"
: "${MYSQL_MIGRATOR_USER:?MYSQL_MIGRATOR_USER required}"
: "${MYSQL_MIGRATOR_PASSWORD:?MYSQL_MIGRATOR_PASSWORD required}"
: "${MYSQL_PLUGIN_REGISTRY_USER:?MYSQL_PLUGIN_REGISTRY_USER required}"
: "${MYSQL_PLUGIN_REGISTRY_PASSWORD:?MYSQL_PLUGIN_REGISTRY_PASSWORD required}"
: "${MYSQL_API_USER:?MYSQL_API_USER required}"
: "${MYSQL_API_PASSWORD:?MYSQL_API_PASSWORD required}"
: "${MYSQL_AUTH_VERIFIER_USER:?MYSQL_AUTH_VERIFIER_USER required}"
: "${MYSQL_AUTH_VERIFIER_PASSWORD:?MYSQL_AUTH_VERIFIER_PASSWORD required}"
: "${MYSQL_SERVICE_IDENTITY_MANAGER_USER:?MYSQL_SERVICE_IDENTITY_MANAGER_USER required}"
: "${MYSQL_SERVICE_IDENTITY_MANAGER_PASSWORD:?MYSQL_SERVICE_IDENTITY_MANAGER_PASSWORD required}"
: "${MYSQL_CREDENTIAL_MANAGER_USER:?MYSQL_CREDENTIAL_MANAGER_USER required}"
: "${MYSQL_CREDENTIAL_MANAGER_PASSWORD:?MYSQL_CREDENTIAL_MANAGER_PASSWORD required}"
: "${MYSQL_PLUGIN_OPERATION_USER:?MYSQL_PLUGIN_OPERATION_USER required}"
: "${MYSQL_PLUGIN_OPERATION_PASSWORD:?MYSQL_PLUGIN_OPERATION_PASSWORD required}"
: "${MYSQL_PREP_CHEF_READER_USER:?MYSQL_PREP_CHEF_READER_USER required}"
: "${MYSQL_PREP_CHEF_READER_PASSWORD:?MYSQL_PREP_CHEF_READER_PASSWORD required}"
: "${MYSQL_TIMER_READER_USER:?MYSQL_TIMER_READER_USER required}"
: "${MYSQL_TIMER_READER_PASSWORD:?MYSQL_TIMER_READER_PASSWORD required}"
: "${MYSQL_EXPEDITER_RUNNER_READER_USER:?MYSQL_EXPEDITER_RUNNER_READER_USER required}"
: "${MYSQL_EXPEDITER_RUNNER_READER_PASSWORD:?MYSQL_EXPEDITER_RUNNER_READER_PASSWORD required}"
: "${MYSQL_DISHWASHER_READER_USER:?MYSQL_DISHWASHER_READER_USER required}"
: "${MYSQL_DISHWASHER_READER_PASSWORD:?MYSQL_DISHWASHER_READER_PASSWORD required}"
: "${MYSQL_READONLY_USER:?MYSQL_READONLY_USER required}"
: "${MYSQL_READONLY_PASSWORD:?MYSQL_READONLY_PASSWORD required}"

MYSQL_INIT_PHASE="${MYSQL_INIT_PHASE:-full}"

mariadb -h"${MYSQL_HOST:-localhost}" -P"${MYSQL_PORT:-3306}" -uroot -p"${MYSQL_ROOT_PASSWORD}" <<EOSQL
CREATE DATABASE IF NOT EXISTS \`${MYSQL_DATABASE}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${MYSQL_MIGRATOR_USER}'@'%' IDENTIFIED BY '${MYSQL_MIGRATOR_PASSWORD}';
CREATE USER IF NOT EXISTS '${MYSQL_PLUGIN_REGISTRY_USER}'@'%' IDENTIFIED BY '${MYSQL_PLUGIN_REGISTRY_PASSWORD}';
CREATE USER IF NOT EXISTS '${MYSQL_API_USER}'@'%' IDENTIFIED BY '${MYSQL_API_PASSWORD}';
CREATE USER IF NOT EXISTS '${MYSQL_AUTH_VERIFIER_USER}'@'%' IDENTIFIED BY '${MYSQL_AUTH_VERIFIER_PASSWORD}';
CREATE USER IF NOT EXISTS '${MYSQL_SERVICE_IDENTITY_MANAGER_USER}'@'%' IDENTIFIED BY '${MYSQL_SERVICE_IDENTITY_MANAGER_PASSWORD}';
CREATE USER IF NOT EXISTS '${MYSQL_CREDENTIAL_MANAGER_USER}'@'%' IDENTIFIED BY '${MYSQL_CREDENTIAL_MANAGER_PASSWORD}';
CREATE USER IF NOT EXISTS '${MYSQL_PLUGIN_OPERATION_USER}'@'%' IDENTIFIED BY '${MYSQL_PLUGIN_OPERATION_PASSWORD}';
CREATE USER IF NOT EXISTS '${MYSQL_PREP_CHEF_READER_USER}'@'%' IDENTIFIED BY '${MYSQL_PREP_CHEF_READER_PASSWORD}';
CREATE USER IF NOT EXISTS '${MYSQL_TIMER_READER_USER}'@'%' IDENTIFIED BY '${MYSQL_TIMER_READER_PASSWORD}';
CREATE USER IF NOT EXISTS '${MYSQL_EXPEDITER_RUNNER_READER_USER}'@'%' IDENTIFIED BY '${MYSQL_EXPEDITER_RUNNER_READER_PASSWORD}';
CREATE USER IF NOT EXISTS '${MYSQL_DISHWASHER_READER_USER}'@'%' IDENTIFIED BY '${MYSQL_DISHWASHER_READER_PASSWORD}';
CREATE USER IF NOT EXISTS '${MYSQL_READONLY_USER}'@'%' IDENTIFIED BY '${MYSQL_READONLY_PASSWORD}';

GRANT ALL PRIVILEGES ON \`${MYSQL_DATABASE}\`.* TO '${MYSQL_MIGRATOR_USER}'@'%';
FLUSH PRIVILEGES;
EOSQL

if [ "${MYSQL_INIT_PHASE}" = "pre_migrate" ]; then
  exit 0
fi

mariadb -h"${MYSQL_HOST:-localhost}" -P"${MYSQL_PORT:-3306}" -uroot -p"${MYSQL_ROOT_PASSWORD}" <<EOSQL
REVOKE ALL PRIVILEGES, GRANT OPTION FROM '${MYSQL_API_USER}'@'%';
REVOKE ALL PRIVILEGES, GRANT OPTION FROM '${MYSQL_AUTH_VERIFIER_USER}'@'%';
REVOKE ALL PRIVILEGES, GRANT OPTION FROM '${MYSQL_PLUGIN_REGISTRY_USER}'@'%';
REVOKE ALL PRIVILEGES, GRANT OPTION FROM '${MYSQL_SERVICE_IDENTITY_MANAGER_USER}'@'%';
REVOKE ALL PRIVILEGES, GRANT OPTION FROM '${MYSQL_READONLY_USER}'@'%';
GRANT SELECT, INSERT, UPDATE ON \`${MYSQL_DATABASE}\`.\`service_plugins\` TO '${MYSQL_PLUGIN_REGISTRY_USER}'@'%';
GRANT SELECT ON \`${MYSQL_DATABASE}\`.\`service_plugins\` TO '${MYSQL_AUTH_VERIFIER_USER}'@'%';
GRANT SELECT ON \`${MYSQL_DATABASE}\`.\`service_identity_credentials\` TO '${MYSQL_AUTH_VERIFIER_USER}'@'%';
GRANT SELECT, INSERT ON \`${MYSQL_DATABASE}\`.\`hmac_nonces\` TO '${MYSQL_AUTH_VERIFIER_USER}'@'%';
GRANT SELECT, UPDATE ON \`${MYSQL_DATABASE}\`.\`service_plugins\` TO '${MYSQL_SERVICE_IDENTITY_MANAGER_USER}'@'%';
GRANT SELECT, INSERT, UPDATE ON \`${MYSQL_DATABASE}\`.\`service_identity_credentials\` TO '${MYSQL_SERVICE_IDENTITY_MANAGER_USER}'@'%';
GRANT SELECT, UPDATE ON \`${MYSQL_DATABASE}\`.\`service_plugins\` TO '${MYSQL_CREDENTIAL_MANAGER_USER}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON \`${MYSQL_DATABASE}\`.\`adapter_credentials\` TO '${MYSQL_CREDENTIAL_MANAGER_USER}'@'%';
GRANT SELECT, UPDATE ON \`${MYSQL_DATABASE}\`.\`service_plugins\` TO '${MYSQL_PLUGIN_OPERATION_USER}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON \`${MYSQL_DATABASE}\`.\`ingredients\` TO '${MYSQL_PLUGIN_OPERATION_USER}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON \`${MYSQL_DATABASE}\`.\`recipes\` TO '${MYSQL_PLUGIN_OPERATION_USER}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON \`${MYSQL_DATABASE}\`.\`recipe_ingredients\` TO '${MYSQL_PLUGIN_OPERATION_USER}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON \`${MYSQL_DATABASE}\`.\`scheduled_tasks\` TO '${MYSQL_PLUGIN_OPERATION_USER}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON \`${MYSQL_DATABASE}\`.\`dishes\` TO '${MYSQL_PLUGIN_OPERATION_USER}'@'%';
GRANT SELECT ON \`${MYSQL_DATABASE}\`.\`service_plugins\` TO '${MYSQL_PREP_CHEF_READER_USER}'@'%';
GRANT SELECT ON \`${MYSQL_DATABASE}\`.\`service_identity_credentials_prep_chef\` TO '${MYSQL_PREP_CHEF_READER_USER}'@'%';
GRANT SELECT ON \`${MYSQL_DATABASE}\`.\`service_plugins\` TO '${MYSQL_TIMER_READER_USER}'@'%';
GRANT SELECT ON \`${MYSQL_DATABASE}\`.\`service_identity_credentials_timer\` TO '${MYSQL_TIMER_READER_USER}'@'%';
GRANT SELECT ON \`${MYSQL_DATABASE}\`.\`service_plugins\` TO '${MYSQL_EXPEDITER_RUNNER_READER_USER}'@'%';
GRANT SELECT ON \`${MYSQL_DATABASE}\`.\`service_identity_credentials_expediter_runner\` TO '${MYSQL_EXPEDITER_RUNNER_READER_USER}'@'%';
GRANT SELECT ON \`${MYSQL_DATABASE}\`.\`service_plugins\` TO '${MYSQL_DISHWASHER_READER_USER}'@'%';
GRANT SELECT ON \`${MYSQL_DATABASE}\`.\`service_identity_credentials_dishwasher\` TO '${MYSQL_DISHWASHER_READER_USER}'@'%';
FLUSH PRIVILEGES;
EOSQL

while IFS= read -r table_name; do
  mariadb -h"${MYSQL_HOST:-localhost}" -P"${MYSQL_PORT:-3306}" -uroot -p"${MYSQL_ROOT_PASSWORD}" <<EOSQL
GRANT SELECT ON \`${MYSQL_DATABASE}\`.\`${table_name}\` TO '${MYSQL_API_USER}'@'%';
EOSQL
done < <(
  mariadb -h"${MYSQL_HOST:-localhost}" -P"${MYSQL_PORT:-3306}" -uroot -p"${MYSQL_ROOT_PASSWORD}" \
    --batch --skip-column-names \
    -e "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='${MYSQL_DATABASE}' AND TABLE_NAME NOT IN ('adapter_credentials','service_identity_credentials','hmac_nonces') AND TABLE_NAME NOT LIKE 'service_identity_credentials_%'"
)

while IFS= read -r table_name; do
  mariadb -h"${MYSQL_HOST:-localhost}" -P"${MYSQL_PORT:-3306}" -uroot -p"${MYSQL_ROOT_PASSWORD}" <<EOSQL
GRANT INSERT, UPDATE, DELETE ON \`${MYSQL_DATABASE}\`.\`${table_name}\` TO '${MYSQL_API_USER}'@'%';
EOSQL
done < <(
  mariadb -h"${MYSQL_HOST:-localhost}" -P"${MYSQL_PORT:-3306}" -uroot -p"${MYSQL_ROOT_PASSWORD}" \
    --batch --skip-column-names \
    -e "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='${MYSQL_DATABASE}' AND TABLE_NAME NOT IN ('adapter_credentials','service_identity_credentials','hmac_nonces') AND TABLE_NAME NOT LIKE 'service_identity_credentials_%'"
)

while IFS= read -r table_name; do
  mariadb -h"${MYSQL_HOST:-localhost}" -P"${MYSQL_PORT:-3306}" -uroot -p"${MYSQL_ROOT_PASSWORD}" <<EOSQL
GRANT SELECT ON \`${MYSQL_DATABASE}\`.\`${table_name}\` TO '${MYSQL_READONLY_USER}'@'%';
EOSQL
done < <(
  mariadb -h"${MYSQL_HOST:-localhost}" -P"${MYSQL_PORT:-3306}" -uroot -p"${MYSQL_ROOT_PASSWORD}" \
    --batch --skip-column-names \
    -e "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='${MYSQL_DATABASE}' AND TABLE_NAME NOT IN ('adapter_credentials','service_identity_credentials','hmac_nonces') AND TABLE_NAME NOT LIKE 'service_identity_credentials_%'"
)

mariadb -h"${MYSQL_HOST:-localhost}" -P"${MYSQL_PORT:-3306}" -uroot -p"${MYSQL_ROOT_PASSWORD}" <<EOSQL
FLUSH PRIVILEGES;
EOSQL
